client_id = "22215140b5ec94721ab323eecabef272"
application_url = "https://reviewnest-production.up.railway.app"

embedded = true
name = "reviewnest"

[access_scopes]
scopes = "write_products,write_metaobjects,write_metaobject_definitions,read_orders"

[auth]
redirect_urls = [ "https://reviewnest-production.up.railway.app/api/auth" ]

[webhooks]
api_version = "2026-10"

  [[webhooks.subscriptions]]
  uri = "https://reviewnest-production.up.railway.app/webhooks/customers/data_request"
  compliance_topics = [ "customers/data_request" ]

  [[webhooks.subscriptions]]
  uri = "https://reviewnest-production.up.railway.app/webhooks/customers/redact"
  compliance_topics = [ "customers/redact" ]

  [[webhooks.subscriptions]]
  uri = "https://reviewnest-production.up.railway.app/webhooks/shop/redact"
  compliance_topics = [ "shop/redact" ]

[product.metafields.app.demo_info]
type = "single_line_text_field"
name = "Demo Source Info"
description = "Tracks products created by the Shopify app template for development"

  [product.metafields.app.demo_info.access]
  admin = "merchant_read_write"

[metaobjects.app.example]
name = "Example"
description = "An example metaobject definition created by this template"

  [metaobjects.app.example.access]
  admin = "merchant_read_write"

[metaobjects.app.example.fields.title]
name = "Title"
type = "single_line_text_field"
required = true

[metaobjects.app.example.fields.description]
name = "Description"
type = "multi_line_text_field"

[build]
automatically_update_urls_on_dev = true