client_id = "22215140b5ec94721ab323eecabef272"
application_url = "https://reviewnest-production.up.railway.app"

embedded = true
name = "reviewnest"

[access_scopes]
scopes = "write_products,write_metaobjects,write_metaobject_definitions,read_orders"

[auth]
redirect_urls = [ "https://reviewnest-production.up.railway.app/api/auth" ]

[build]
automatically_update_urls_on_dev = true