api_version = "2024-10"

[[extensions]]
type = "theme"
name = "review-widget"
handle = "review-widget"
uid = "35b372b8-e5d7-81eb-c3d7-dea12634b8c97c864dfc"

[extensions.capabilities]
network_access = true